import type { EmployeeRow, RefreshSettings } from "./refreshSizing";
import { defaultGuidelines, defaultSettings } from "./refreshSizing";

/**
 * Sample population for the refresh-sizing demo. Picked to surface
 * every exception type:
 *   - In-band MEETS (no exception)
 *   - Above-band TOP with critical role (RETENTION_OVERRIDE + ABOVE_GUIDELINE)
 *   - Way above (WAY_ABOVE_GUIDELINE)
 *   - Below-band HIGH (BELOW_GUIDELINE)
 *   - Way below (WAY_BELOW_GUIDELINE)
 *   - Stale last grant
 *   - Missing level
 *   - Off-matrix level (MISSING_GUIDELINE)
 *   - Zero-value proposed
 *   - Per-row FMV override
 *   - Manager override; large, justified
 *
 * The numbers are deliberately mid-cycle realistic — not extreme — so a
 * first-time visitor sees a believable distribution rather than a row
 * of red flags.
 */
export const SAMPLE_ROWS: EmployeeRow[] = [
  {
    rowId: "s-001",
    employeeId: "E1001",
    employeeName: "A. Patel",
    level: "L5",
    country: "US",
    currentEquityValue: 180000,
    unvestedValue: 110000,
    lastGrantDate: "2025-02-15",
    priorRefreshDollars: 32000,
    performanceTier: "MEETS",
    retentionRisk: "MEDIUM",
    criticalRoleFlag: false,
    proposedRefreshDollars: 38000,
    vestingPattern: "4yr 25/25/25/25",
  },
  {
    rowId: "s-002",
    employeeId: "E1002",
    employeeName: "B. Nguyen",
    level: "L5",
    country: "US",
    currentEquityValue: 240000,
    unvestedValue: 150000,
    lastGrantDate: "2025-02-15",
    priorRefreshDollars: 45000,
    performanceTier: "TOP",
    retentionRisk: "HIGH",
    criticalRoleFlag: true,
    proposedRefreshDollars: 64000,
    vestingPattern: "4yr 25/25/25/25",
    notes: "Lead on customer-data migration; replacement timeline 6+ months.",
  },
  {
    rowId: "s-003",
    employeeId: "E1003",
    employeeName: "C. Romero",
    level: "L6",
    country: "US",
    currentEquityValue: 380000,
    unvestedValue: 240000,
    lastGrantDate: "2025-02-15",
    priorRefreshDollars: 70000,
    performanceTier: "HIGH",
    retentionRisk: "MEDIUM",
    criticalRoleFlag: false,
    proposedRefreshDollars: 78000,
    vestingPattern: "4yr 25/25/25/25",
  },
  {
    rowId: "s-004",
    employeeId: "E1004",
    employeeName: "D. Park",
    level: "L6",
    country: "US",
    currentEquityValue: 410000,
    unvestedValue: 280000,
    lastGrantDate: "2024-02-15",
    priorRefreshDollars: 80000,
    performanceTier: "HIGH",
    retentionRisk: "HIGH",
    criticalRoleFlag: true,
    proposedRefreshDollars: 130000,
    vestingPattern: "4yr 25/25/25/25",
    notes: "Recruiter outreach intercepted last quarter.",
  },
  {
    rowId: "s-005",
    employeeId: "E1005",
    employeeName: "E. Kim",
    level: "L4",
    country: "IE",
    currentEquityValue: 90000,
    unvestedValue: 60000,
    lastGrantDate: "2025-02-15",
    priorRefreshDollars: 18000,
    performanceTier: "HIGH",
    retentionRisk: "LOW",
    criticalRoleFlag: false,
    proposedRefreshDollars: 18000,
    vestingPattern: "4yr 25/25/25/25",
  },
  {
    rowId: "s-006",
    employeeId: "E1006",
    employeeName: "F. Adeyemi",
    level: "L5",
    country: "US",
    currentEquityValue: 150000,
    unvestedValue: 75000,
    lastGrantDate: "2023-02-15",
    priorRefreshDollars: 30000,
    performanceTier: "MEETS",
    retentionRisk: "MEDIUM",
    criticalRoleFlag: false,
    proposedRefreshDollars: 36000,
    vestingPattern: "4yr 25/25/25/25",
  },
  {
    rowId: "s-007",
    employeeId: "E1007",
    employeeName: "G. Bauer",
    level: "M6",
    country: "DE",
    currentEquityValue: 540000,
    unvestedValue: 360000,
    lastGrantDate: "2025-02-15",
    priorRefreshDollars: 95000,
    performanceTier: "TOP",
    retentionRisk: "MEDIUM",
    criticalRoleFlag: false,
    proposedRefreshDollars: 110000,
    vestingPattern: "4yr 25/25/25/25",
  },
  {
    rowId: "s-008",
    employeeId: "E1008",
    employeeName: "H. Singh",
    level: "L7",
    country: "US",
    currentEquityValue: 720000,
    unvestedValue: 480000,
    lastGrantDate: "2025-02-15",
    priorRefreshDollars: 110000,
    performanceTier: "HIGH",
    retentionRisk: "MEDIUM",
    criticalRoleFlag: false,
    proposedRefreshDollars: 50000,
    vestingPattern: "4yr 25/25/25/25",
    notes: "Manager flagged extended sabbatical impact; revisit in mid-year.",
  },
  {
    rowId: "s-009",
    employeeId: "E1009",
    employeeName: "I. Yamamoto",
    level: "",
    country: "JP",
    currentEquityValue: 0,
    unvestedValue: 0,
    lastGrantDate: undefined,
    priorRefreshDollars: 0,
    performanceTier: "MEETS",
    retentionRisk: "UNKNOWN",
    criticalRoleFlag: false,
    proposedRefreshDollars: undefined,
    vestingPattern: undefined,
  },
  {
    rowId: "s-010",
    employeeId: "E1010",
    employeeName: "J. Carter",
    level: "L9",
    country: "US",
    currentEquityValue: 950000,
    unvestedValue: 650000,
    lastGrantDate: "2025-02-15",
    priorRefreshDollars: 200000,
    performanceTier: "HIGH",
    retentionRisk: "MEDIUM",
    criticalRoleFlag: false,
    proposedRefreshDollars: 250000,
    vestingPattern: "4yr 25/25/25/25",
    notes: "Recently promoted; level not yet in matrix.",
  },
  {
    rowId: "s-011",
    employeeId: "E1011",
    employeeName: "K. Olsen",
    level: "L4",
    country: "US",
    currentEquityValue: 0,
    unvestedValue: 0,
    lastGrantDate: "2024-04-01",
    priorRefreshDollars: 0,
    performanceTier: "BELOW",
    retentionRisk: "LOW",
    criticalRoleFlag: false,
    proposedRefreshDollars: 0,
    vestingPattern: "4yr 25/25/25/25",
    notes: "Performance plan in progress; no refresh proposed this cycle.",
  },
  {
    rowId: "s-012",
    employeeId: "E1012",
    employeeName: "L. Tanaka",
    level: "L5",
    country: "JP",
    currentEquityValue: 200000,
    unvestedValue: 100000,
    lastGrantDate: "2025-02-15",
    priorRefreshDollars: 35000,
    performanceTier: "EMERGING",
    retentionRisk: "MEDIUM",
    criticalRoleFlag: false,
    proposedRefreshDollars: 22000,
    vestingPattern: "4yr 25/25/25/25",
  },
  {
    rowId: "s-013",
    employeeId: "E1013",
    employeeName: "M. Ahmed",
    level: "M5",
    country: "AE",
    currentEquityValue: 280000,
    unvestedValue: 180000,
    lastGrantDate: "2025-02-15",
    priorRefreshDollars: 50000,
    performanceTier: "HIGH",
    retentionRisk: "MEDIUM",
    criticalRoleFlag: false,
    proposedRefreshDollars: 58000,
    vestingPattern: "4yr 25/25/25/25",
  },
  {
    rowId: "s-014",
    employeeId: "E1014",
    employeeName: "N. Owusu",
    level: "L4",
    country: "US",
    currentEquityValue: 100000,
    unvestedValue: 70000,
    lastGrantDate: "2025-02-15",
    priorRefreshDollars: 20000,
    performanceTier: "MEETS",
    retentionRisk: "LOW",
    criticalRoleFlag: false,
    proposedRefreshDollars: 22000,
    vestingPattern: "4yr 25/25/25/25",
  },
  {
    rowId: "s-015",
    employeeId: "E1015",
    employeeName: "O. Larsen",
    level: "L5",
    country: "DK",
    currentEquityValue: 195000,
    unvestedValue: 130000,
    lastGrantDate: "2025-02-15",
    priorRefreshDollars: 36000,
    performanceTier: "MEETS",
    retentionRisk: "MEDIUM",
    criticalRoleFlag: false,
    proposedRefreshDollars: 38000,
    fmvPerShare: 48,
    vestingPattern: "4yr 25/25/25/25",
    notes: "Per-row FMV override (local-currency-quoted plan).",
  },
];

/** Default sample settings: $50 FMV, $1.5M budget, 24-month stale threshold. */
export function sampleSettings(): RefreshSettings {
  return {
    ...defaultSettings(),
    fmvPerShare: 50,
    totalBudget: 1500000,
    staleGrantThresholdMonths: 24,
    asOfDate: "2026-05-08",
    shareRoundingIncrement: 1,
  };
}

export const SAMPLE_GUIDELINES = defaultGuidelines();
